test:
  Good:
    Real:
      category: Good
      hash:
      - current_version
      n_images: 5310
      split: test
      versions:
      - A
train:
  Good:
    Real:
      category: Good
      hash:
      - current_version
      n_images: 42420
      split: train
      versions:
      - A
val:
  Good:
    Real:
      category: Good
      hash:
      - current_version
      n_images: 5310
      split: val
      versions:
      - A