test:
  CC:
    Real:
      category: F1
      hash:
      - current_version
      n_images: 1710
      split: test
      versions:
      - A
      - B
      - C
  DPCake:
    Real:
      category: D1
      hash:
      - current_version
      n_images: 724
      split: test
      versions:
      - A
      - B
      - C
      - D
  GPCake:
    Real:
      category: D1
      hash:
      - current_version
      n_images: 210
      split: test
      versions:
      - A
  Good:
    Real:
      category: Good
      hash:
      - current_version
      n_images: 5310
      split: test
      versions:
      - A
  SPCake:
    Real:
      category: D1
      hash:
      - current_version
      n_images: 261
      split: test
      versions:
      - A
      - B
      - C
train:
  CC:
    Synthetic:
      category: F1
      hash:
      - version4
      n_images: 46000
      split: train
      versions: []
  DPCake:
    Synthetic:
      category: D1
      hash:
      - version3
      - version4
      n_images: 527000
      split: train
      versions: []
  GPCake:
    Synthetic:
      category: D1
      hash:
      - v0.1 - gpcake - 6cdb393
      - v0.1 - main - 7ab7a05
      - v0.1-gpcake-6c5d1ec
      - version3
      - version4
      n_images: 1070699
      split: train
      versions: []
  SPCake:
    Synthetic:
      category: D1
      hash:
      - v0.1 - DPCakeShade - 932a0de
      - version4
      n_images: 712108
      split: train
      versions: []
val:
  CC:
    Real:
      category: F1
      hash:
      - current_version
      n_images: 420
      split: val
      versions:
      - A
      - B
      - C
  DPCake:
    Real:
      category: D1
      hash:
      - current_version
      n_images: 158
      split: val
      versions:
      - A
      - B
      - C
      - D
  GPCake:
    Real:
      category: D1
      hash:
      - current_version
      n_images: 36
      split: val
      versions:
      - A
  Good:
    Real:
      category: Good
      hash:
      - current_version
      n_images: 5310
      split: val
      versions:
      - A
  SPCake:
    Real:
      category: D1
      hash:
      - current_version
      n_images: 29
      split: val
      versions:
      - A
      - B
      - C
