state:
  mode: train
  load: False
  version_hparams: [dataset_type, batch_size, timesteps]

model:
  lr: 5e-4
  weight_decay: 1e-6
  patience: 1000
  max_epochs: 3000
  num_defects: None
  defect_names: None
  model_name: ConditionalDiffusionNet
  dim_mults: [1, 2, 2, 2]
  img_size: 32
  channels: 3
  timesteps: 200
  batch_size: 1536

dataset:
  data_path: /nn-seidenader-gentofte/TJSD/VisData
  camera: 2
  weighted_sampling: 1
  num_workers: 8
  batch_size: 1536
  img_size: 32
  dataset_type: Synthetic
  transform:

      