training:
  max_epochs: 20
  lr: 1e-5

model:
  model_name: MixNMatch

dataset:
  data_path: /nn-seidenader-gentofte/Data
  camera: 2
  num_workers: 1
  batch_size: 32
  img_size: 128
  train:
    categories:
      B:
        origin: Synthetic
        n_images: 2000
        hash: v0.1 - beak - fc348f8
        versions:
          - ""
        split: train
      Good:
        origin: Real
        n_images: 2000
        hash: current_version
        versions:
          - A
        split: train
  val:
    categories:
      B:
        origin: Real
        n_images: 300
        hash: current_version
        versions:
          - E
        split: validation_DOD_10
      Good:
        origin: Real
        n_images: 300
        hash: "current_version"
        versions:
          - A
        split: train
  transform:
      