state:
  mode: train
  load: True
  version_hparams: [dataset_type, batch_size, timesteps]

model:
  lr: 1e-3
  patience: 1000
  max_epochs: 3000
  num_classes: None
  class_names: None
  model_name: DiffusionNet
  dim_mults: [1, 2, 2, 2]
  channels: 3
  timesteps: 200
  batch_size: 256
  img_size: 64

dataset:
  data_path: /nn-seidenader-gentofte/TJSD/VisData
  camera: 3
  weighted_sampling: 0
  num_workers: 10
  batch_size: 256
  img_size: 64
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
  dataset_type: Real_Good
  transform:

      