state:
  mode: train
  load: False
  version_hparams: [dataset_type, batch_size, timesteps]
  model_name: DiffusionNet

model:
  lr: 3e-4
  patience: 1000
  max_epochs: 3000
  num_classes: None
  class_names: None
  model_name: DiffusionNet
  dim_mults: [1, 2, 3]
  channels: 3
  timesteps: 150
  batch_size: 256
  img_size: 64

dataset:
  data_path: /nn-seidenader-gentofte/TJSD/VisData
  camera: 3
  weighted_sampling: 0
  num_workers: 10
  batch_size: 256
  img_size: 64
  mean: [0.5, 0.5, 0.5]
  std: [0.5, 0.5, 0.5]
  dataset_type: Real_Good
  transform:

      