state:
  mode: train
  load: False
  version_hparams: [dataset_type, batch_size, timesteps]

model:
  lr: 1e-3
  patience: 100
  max_epochs: 304
  num_classes: None
  class_names: None
  model_name: DiffusionNet
  dim_mults: [1, 2, 2, 2]
  img_size: 32
  channels: 3
  timesteps: 200
  batch_size: 512

dataset:
  data_path: /nn-seidenader-gentofte/TJSD/VisData
  camera: 3
  weighted_sampling: 0
  num_workers: 8
  batch_size: 512
  img_size: 32
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
  dataset_type: Real_Good
  transform:

      