state:
  mode: train
  load: False
  version_hparams: [dataset_type, batch_size, timesteps]
  model_name: DiffusionNet

model:
  lr: 1e-3
  patience: 1000
  max_epochs: 3000
  num_classes: None
  class_names: None
  dim_mults: [1, 2, 2, 2]
  channels: 3
  timesteps: 200
  batch_size:
  img_size:

dataset:
  data_path: /nn-seidenader-gentofte/TJSD/VisData
  camera: 3
  weighted_sampling: 0
  num_workers: 10
  batch_size: 256
  img_size: 64
  dataset_type: Real_Good
  transform:

      