state:
  mode: train
  load: False
  # load_epoch: 14
  version_hparams: [dataset_type, batch_size, channels, image_size, cond_stage_key]
  model_name: LatentDiffusion
  monitor: val/loss_simple_ema
  gpu: [0]
  save_last: True
  gradient_accum: 8
  precision: 

model:
  accum_gradients: True
  lr: 1.0e-06
  patience: 5
  max_epochs: 50
  num_defects: None
  defect_names: None

  linear_start: 0.0015
  linear_end: 0.0205
  num_timesteps_cond: 1
  log_every_t: 200
  timesteps: 1000
  first_stage_key: 0
  cond_stage_key: 
    c_concat: 3
    c_crossattn: 2
  image_size: 32
  channels: 3
  cond_stage_trainable: true
  conditioning_key: hybrid
  monitor: val/loss_epoch

  first_stage_config:
    first_stage_model: VQModelInterface
    n_embed: 16384
    latent_dim: 3
    ckpt_path: tb_logs\VQModel_CAM2\dattyp_batsiz_latdim_nemb_numdef\Real_Synthetic_8_3_16384_14\model_epoch=15_val_loss=0.000.ckpt
    AEcfg:
      double_z: False
      z_channels: 3
      img_size: 256
      channels: 3
      out_ch: 3
      init_dim: 128
      dim_mult: [1, 2, 4, 4]
      num_res_blocks: 2
      attn_resolutions: []
      resnet_block_groups: 8
    losscfg: identity
  unet_config:
    image_size: 32
    in_channels: 3
    out_channels: 3
    model_channels: 256
    attention_resolutions: [8, 4, 1]
    num_res_blocks: 2
    channel_mult: [1, 2, 3, 4]
    num_head_channels: 8
    use_spatial_transformer: true
    transformer_depth: 1
    resblock_updown: True
    context_dim: 9
  cond_stage_config:
    embed_dim: 9
    key: 2
    n_classes:
  spatial_config:
    n_stages: 4
    multiplier: 0.5
    in_channels: 1

dataset:
  data_path: /nn-seidenader-gentofte/TJSD/VisData
  camera: 2
  weighted_sampling: 1
  num_workers: 5
  batch_size: 5
  img_size: 256
  loader: VialNBBoxLoader
  dataset_type: Real_Synthetic
  transform: 

      