state:
  mode: train
  load: True
  version_hparams: [dataset_type, batch_size, latent_dim, n_embed]
  model_name: VQModel
  monitor: val_rec_loss
  save_last: True
  gpu: [0]
  precision: mixed

model:
  lr: 4.5e-06
  patience: 10
  max_epochs: 50
  num_defects: None
  defect_names: None
  latent_dim: 3
  n_embed: 16384
  losscfg:
    disc_conditional: false
    disc_in_channels: 3
    disc_start: 1
    disc_weight: 0.75
    disc_num_layers: 2
    codebook_weight: 1.0
  AEcfg:
    double_z: False
    z_channels: 3
    img_size: 256
    channels: 3
    out_ch: 3
    init_dim: 128
    dim_mult: [1, 2, 4, 4]
    num_res_blocks: 2
    attn_resolutions: []
    resnet_block_groups: 8

dataset:
  data_path: /nn-seidenader-gentofte/TJSD/VisData
  camera: 2
  weighted_sampling: 1
  num_workers: 8
  batch_size: 8
  img_size: 256
  dataset_type: Real_Synthetic
  transform:

      