test:
  B:
    Real:
      category: A2
      hash:
      - current_version
      n_images: 894
      split: test
      versions:
      - A
      - B
      - C
      - D
      - E
  CCD:
    Real:
      category: A3
      hash:
      - current_version
      n_images: 2100
      split: test
      versions:
      - A
      - B
      - C
      - D
      - E
      - F
      - G
      - H
      - I
  ChipSh:
    Real:
      category: C1
      hash:
      - current_version
      n_images: 103
      split: test
      versions:
      - A
      - B
      - C
      - E
  CnC:
    Real:
      category: A1
      hash:
      - current_version
      n_images: 960
      split: test
      versions:
      - A
      - B
      - C
  DIST:
    Real:
      category: B2
      hash:
      - current_version
      n_images: 493
      split: test
      versions:
      - A
      - B
      - E
  DPPST:
    Real:
      category: D1
      hash:
      - current_version
      n_images: 203
      split: test
      versions:
      - A
      - B
  FCC:
    Real:
      category: A2
      hash:
      - current_version
      n_images: 1039
      split: test
      versions:
      - A
      - B
      - C
  FMI:
    Real:
      category: D1
      hash:
      - current_version
      n_images: 33
      split: test
      versions:
      - A
      - B
  FMOV:
    Real:
      category: C2
      hash:
      - current_version
      n_images: 361
      split: test
      versions:
      - A
      - E
  FOST:
    Real:
      category: D1
      hash:
      - current_version
      n_images: 1431
      split: test
      versions:
      - A
      - B
  GPST:
    Real:
      category: D1
      hash:
      - current_version
      n_images: 183
      split: test
      versions:
      - A
  Good:
    Real:
      category: Good
      hash:
      - current_version
      n_images: 21720
      split: test
      versions:
      - A
      - B
      - C
      - D
      - E
  ICFC:
    Real:
      category: A2
      hash:
      - current_version
      n_images: 930
      split: test
      versions:
      - A
      - B
      - C
  LCC:
    Real:
      category: A1
      hash:
      - current_version
      n_images: 1145
      split: test
      versions:
      - A
      - B
  MESM:
    Real:
      category: B2
      hash:
      - current_version
      n_images: 114
      split: test
      versions:
      - A
  MSF:
    Real:
      category: B1
      hash:
      - current_version
      n_images: 480
      split: test
      versions:
      - A
  MST:
    Real:
      category: B1
      hash:
      - current_version
      n_images: 480
      split: test
      versions:
      - A
  PST:
    Real:
      category: G1
      hash:
      - current_version
      n_images: 235
      split: test
      versions:
      - A
      - B
      - C
      - D
  SSNPDNeck:
    Real:
      category: C2
      hash:
      - current_version
      n_images: 260
      split: test
      versions:
      - A
      - C
      - D
train:
  B:
    Diffusion:
      category: A2
      hash:
      - Real_generative_5_256_4_19
      n_images: 1000
      split: train
      versions: []
    Synthetic:
      category: A2
      hash:
      - v0.1 - beak - fc348f8
      n_images: 2264
      split: train
      versions: []
  CCD:
    Diffusion:
      category: A3
      hash:
      - Real_generative_5_256_4_19
      n_images: 1000
      split: train
      versions: []
    Synthetic:
      category: A3
      hash:
      - v5
      n_images: 2500
      split: train
      versions: []
  ChipSh:
    Diffusion:
      category: C1
      hash:
      - Real_generative_5_256_4_19
      n_images: 1000
      split: train
      versions: []
  CnC:
    Diffusion:
      category: A1
      hash:
      - Real_generative_5_256_4_19
      n_images: 1000
      split: train
      versions: []
    Synthetic:
      category: A1
      hash:
      - v0.1 - HEAD - 8d9eecd
      n_images: 1000
      split: train
      versions: []
  DIST:
    Diffusion:
      category: B2
      hash:
      - Real_generative_5_256_4_19
      n_images: 1000
      split: train
      versions: []
    Synthetic:
      category: B2
      hash:
      - v0.1 - HEAD - 2b9ac9c
      - v0.1 - Reflectionfix - e565b93a
      n_images: 2298
      split: train
      versions: []
  DPPST:
    Diffusion:
      category: D1
      hash:
      - Real_generative_5_256_4_19
      n_images: 1000
      split: train
      versions: []
    Synthetic:
      category: D1
      hash:
      - v0.1 - NewParticleStopper - 0466cf31
      n_images: 4996
      split: train
      versions: []
  FCC:
    Diffusion:
      category: A2
      hash:
      - Real_generative_5_256_4_19
      n_images: 1000
      split: train
      versions: []
    Synthetic:
      category: A2
      hash:
      - v0.1 - A1A2merged - 8d9eecd
      n_images: 1000
      split: train
      versions: []
  FMI:
    Diffusion:
      category: D1
      hash:
      - Real_generative_5_256_4_19
      n_images: 1000
      split: train
      versions: []
  FMOV:
    Diffusion:
      category: C2
      hash:
      - Real_generative_5_256_4_19
      n_images: 1000
      split: train
      versions: []
  FOST:
    Diffusion:
      category: D1
      hash:
      - Real_generative_5_256_4_19
      n_images: 1000
      split: train
      versions: []
    Synthetic:
      category: D1
      hash:
      - v0.1 - main - 3de6d5f2
      n_images: 2000
      split: train
      versions: []
  GPST:
    Diffusion:
      category: D1
      hash:
      - Real_generative_5_256_4_19
      n_images: 1000
      split: train
      versions: []
    Synthetic:
      category: D1
      hash:
      - v0.1 - gpst - 59f35e4
      - v0.1 - NewParticleStopper - 0466cf31
      n_images: 8093
      split: train
      versions: []
  Good:
    Diffusion:
      category: Good
      hash:
      - Real_generative_5_256_4_19
      n_images: 1000
      split: train
      versions: []
    Synthetic:
      category: Good
      hash:
      - v0.1 - HEAD - 2b9ac9c
      n_images: 1940
      split: train
      versions: []
  ICFC:
    Diffusion:
      category: A2
      hash:
      - Real_generative_5_256_4_19
      n_images: 1000
      split: train
      versions: []
  LCC:
    Diffusion:
      category: A1
      hash:
      - Real_generative_5_256_4_19
      n_images: 1000
      split: train
      versions: []
  MESM:
    Diffusion:
      category: B2
      hash:
      - Real_generative_5_256_4_19
      n_images: 1000
      split: train
      versions: []
    Synthetic:
      category: B2
      hash:
      - v0.1 - FOSTfix - 3986acad
      n_images: 2000
      split: train
      versions: []
  MSF:
    Diffusion:
      category: B1
      hash:
      - Real_generative_5_256_4_19
      n_images: 1000
      split: train
      versions: []
    Synthetic:
      category: B1
      hash:
      - v0.1 - main - 8e82c19
      n_images: 2000
      split: train
      versions: []
  MST:
    Diffusion:
      category: B1
      hash:
      - Real_generative_5_256_4_19
      n_images: 1000
      split: train
      versions: []
    Synthetic:
      category: B1
      hash:
      - v0.1 - FOSTfix - 3986acad
      n_images: 1000
      split: train
      versions: []
  PST:
    Diffusion:
      category: G1
      hash:
      - Real_generative_5_256_4_19
      n_images: 1000
      split: train
      versions: []
    Synthetic:
      category: G1
      hash:
      - v0.1 - main - 3de6d5f2
      n_images: 1999
      split: train
      versions: []
  SSNPDNeck:
    Diffusion:
      category: C2
      hash:
      - Real_generative_5_256_4_19
      n_images: 1000
      split: train
      versions: []
    Synthetic:
      category: C2
      hash:
      - v0.1 - SSNPDCake - 2b02fc5
      - v0.1 - SSNPDCake - 700e8ce
      n_images: 3037
      split: train
      versions: []
val:
  B:
    Real:
      category: A2
      hash:
      - current_version
      n_images: 225
      split: val
      versions:
      - A
      - B
      - C
      - D
      - E
  CCD:
    Real:
      category: A3
      hash:
      - current_version
      n_images: 450
      split: val
      versions:
      - A
      - B
      - C
      - D
      - E
      - F
      - G
      - H
      - I
  ChipSh:
    Real:
      category: C1
      hash:
      - current_version
      n_images: 0
      split: val
      versions:
      - A
      - B
      - C
      - E
  CnC:
    Real:
      category: A1
      hash:
      - current_version
      n_images: 240
      split: val
      versions:
      - A
      - B
      - C
  DIST:
    Real:
      category: B2
      hash:
      - current_version
      n_images: 89
      split: val
      versions:
      - A
      - B
      - E
  DPPST:
    Real:
      category: D1
      hash:
      - current_version
      n_images: 47
      split: val
      versions:
      - A
      - B
  FCC:
    Real:
      category: A2
      hash:
      - current_version
      n_images: 267
      split: val
      versions:
      - A
      - B
      - C
  FMI:
    Real:
      category: D1
      hash:
      - current_version
      n_images: 9
      split: val
      versions:
      - A
      - B
  FMOV:
    Real:
      category: C2
      hash:
      - current_version
      n_images: 103
      split: val
      versions:
      - A
      - E
  FOST:
    Real:
      category: D1
      hash:
      - current_version
      n_images: 372
      split: val
      versions:
      - A
      - B
  GPST:
    Real:
      category: D1
      hash:
      - current_version
      n_images: 38
      split: val
      versions:
      - A
  Good:
    Real:
      category: Good
      hash:
      - current_version
      n_images: 21840
      split: val
      versions:
      - A
      - B
      - C
      - D
      - E
  ICFC:
    Real:
      category: A2
      hash:
      - current_version
      n_images: 180
      split: val
      versions:
      - A
      - B
      - C
  LCC:
    Real:
      category: A1
      hash:
      - current_version
      n_images: 248
      split: val
      versions:
      - A
      - B
  MESM:
    Real:
      category: B2
      hash:
      - current_version
      n_images: 38
      split: val
      versions:
      - A
  MSF:
    Real:
      category: B1
      hash:
      - current_version
      n_images: 120
      split: val
      versions:
      - A
  MST:
    Real:
      category: B1
      hash:
      - current_version
      n_images: 90
      split: val
      versions:
      - A
  PST:
    Real:
      category: G1
      hash:
      - current_version
      n_images: 24
      split: val
      versions:
      - A
      - B
      - C
      - D
  SSNPDNeck:
    Real:
      category: C2
      hash:
      - current_version
      n_images: 34
      split: val
      versions:
      - A
      - C
      - D
