test:
  B:
    Real:
      category: A2
      hash:
      - current_version
      n_images: 894
      split: test
      versions:
      - A
      - B
      - C
      - D
      - E
  CCD:
    Real:
      category: A3
      hash:
      - current_version
      n_images: 2100
      split: test
      versions:
      - A
      - B
      - C
      - D
      - E
      - F
      - G
      - H
      - I
  CnC:
    Real:
      category: A1
      hash:
      - current_version
      n_images: 960
      split: test
      versions:
      - A
      - B
      - C
  DIST:
    Real:
      category: B2
      hash:
      - current_version
      n_images: 493
      split: test
      versions:
      - A
      - B
      - E
  DPPST:
    Real:
      category: D1
      hash:
      - current_version
      n_images: 203
      split: test
      versions:
      - A
      - B
  FCC:
    Real:
      category: A2
      hash:
      - current_version
      n_images: 1039
      split: test
      versions:
      - A
      - B
      - C
  FOST:
    Real:
      category: D1
      hash:
      - current_version
      n_images: 1431
      split: test
      versions:
      - A
      - B
  GPST:
    Real:
      category: D1
      hash:
      - current_version
      n_images: 183
      split: test
      versions:
      - A
  Good:
    Real:
      category: Good
      hash:
      - current_version
      n_images: 21720
      split: test
      versions:
      - A
      - B
      - C
      - D
      - E
  MESM:
    Real:
      category: B2
      hash:
      - current_version
      n_images: 114
      split: test
      versions:
      - A
  MSF:
    Real:
      category: B1
      hash:
      - current_version
      n_images: 480
      split: test
      versions:
      - A
  MST:
    Real:
      category: B1
      hash:
      - current_version
      n_images: 480
      split: test
      versions:
      - A
  PST:
    Real:
      category: G1
      hash:
      - current_version
      n_images: 235
      split: test
      versions:
      - A
      - B
      - C
      - D
  SSNPDNeck:
    Real:
      category: C2
      hash:
      - current_version
      n_images: 260
      split: test
      versions:
      - A
      - C
      - D
train:
  B:
    DiffusionImg2Img:
      category: A2
      hash:
      - Real_Synthetic_16_3_32_hybrid_28_img2img_steps=49_funfun
      n_images: 2000
      split: train
      versions: []
    Real:
      category: A2
      hash:
      - current_version
      n_images: 1006
      split: train
      versions:
      - A
      - B
      - C
      - D
      - E
  CCD:
    DiffusionImg2Img:
      category: A3
      hash:
      - Real_Synthetic_16_3_32_hybrid_28_img2img_steps=49_funfun
      n_images: 2000
      split: train
      versions: []
    Real:
      category: A3
      hash:
      - current_version
      n_images: 2372
      split: train
      versions:
      - A
      - B
      - C
      - D
      - E
      - F
      - G
      - H
      - I
  CnC:
    DiffusionImg2Img:
      category: A1
      hash:
      - Real_Synthetic_16_3_32_hybrid_28_img2img_steps=49_funfun
      n_images: 2000
      split: train
      versions: []
    Real:
      category: A1
      hash:
      - current_version
      n_images: 1098
      split: train
      versions:
      - A
      - B
      - C
  DIST:
    DiffusionImg2Img:
      category: B2
      hash:
      - Real_Synthetic_16_3_32_hybrid_28_img2img_steps=49_funfun
      n_images: 4000
      split: train
      versions: []
    Real:
      category: B2
      hash:
      - current_version
      n_images: 658
      split: train
      versions:
      - A
      - B
      - E
  DPPST:
    DiffusionImg2Img:
      category: D1
      hash:
      - Real_Synthetic_16_3_32_hybrid_28_img2img_steps=49_funfun
      n_images: 2000
      split: train
      versions: []
    Real:
      category: D1
      hash:
      - current_version
      n_images: 209
      split: train
      versions:
      - A
      - B
  FCC:
    DiffusionImg2Img:
      category: A2
      hash:
      - Real_Synthetic_16_3_32_hybrid_28_img2img_steps=49_funfun
      n_images: 2000
      split: train
      versions: []
    Real:
      category: A2
      hash:
      - current_version
      n_images: 1193
      split: train
      versions:
      - A
      - B
      - C
  FOST:
    DiffusionImg2Img:
      category: D1
      hash:
      - Real_Synthetic_16_3_32_hybrid_28_img2img_steps=49_funfun
      n_images: 2000
      split: train
      versions: []
    Real:
      category: D1
      hash:
      - current_version
      n_images: 1843
      split: train
      versions:
      - A
      - B
  GPST:
    DiffusionImg2Img:
      category: D1
      hash:
      - Real_Synthetic_16_3_32_hybrid_28_img2img_steps=49_funfun
      n_images: 2000
      split: train
      versions: []
    Real:
      category: D1
      hash:
      - current_version
      n_images: 217
      split: train
      versions:
      - A
  Good:
    DiffusionImg2Img:
      category: Good
      hash:
      - Real_Synthetic_16_3_32_hybrid_28_img2img_steps=49_funfun
      n_images: 2000
      split: train
      versions: []
    Real:
      category: Good
      hash:
      - current_version
      n_images: 171870
      split: train
      versions:
      - A
      - B
      - C
      - D
      - E
  MESM:
    DiffusionImg2Img:
      category: B2
      hash:
      - Real_Synthetic_16_3_32_hybrid_28_img2img_steps=49_funfun
      n_images: 2000
      split: train
      versions: []
    Real:
      category: B2
      hash:
      - current_version
      n_images: 168
      split: train
      versions:
      - A
  MSF:
    DiffusionImg2Img:
      category: B1
      hash:
      - Real_Synthetic_16_3_32_hybrid_28_img2img_steps=49_funfun
      n_images: 816
      split: train
      versions: []
    Real:
      category: B1
      hash:
      - current_version
      n_images: 570
      split: train
      versions:
      - A
  MST:
    DiffusionImg2Img:
      category: B1
      hash:
      - Real_Synthetic_16_3_32_hybrid_28_img2img_steps=49_funfun
      n_images: 2000
      split: train
      versions: []
    Real:
      category: B1
      hash:
      - current_version
      n_images: 570
      split: train
      versions:
      - A
  PST:
    DiffusionImg2Img:
      category: G1
      hash:
      - Real_Synthetic_16_3_32_hybrid_28_img2img_steps=49_funfun
      n_images: 2000
      split: train
      versions: []
    Real:
      category: G1
      hash:
      - current_version
      n_images: 307
      split: train
      versions:
      - A
      - B
      - C
      - D
  SSNPDNeck:
    DiffusionImg2Img:
      category: C2
      hash:
      - Real_Synthetic_16_3_32_hybrid_28_img2img_steps=49_funfun
      n_images: 2000
      split: train
      versions: []
    Real:
      category: C2
      hash:
      - current_version
      n_images: 270
      split: train
      versions:
      - A
      - C
      - D
val:
  B:
    Real:
      category: A2
      hash:
      - current_version
      n_images: 225
      split: val
      versions:
      - A
      - B
      - C
      - D
      - E
  CCD:
    Real:
      category: A3
      hash:
      - current_version
      n_images: 450
      split: val
      versions:
      - A
      - B
      - C
      - D
      - E
      - F
      - G
      - H
      - I
  CnC:
    Real:
      category: A1
      hash:
      - current_version
      n_images: 240
      split: val
      versions:
      - A
      - B
      - C
  DIST:
    Real:
      category: B2
      hash:
      - current_version
      n_images: 89
      split: val
      versions:
      - A
      - B
      - E
  DPPST:
    Real:
      category: D1
      hash:
      - current_version
      n_images: 47
      split: val
      versions:
      - A
      - B
  FCC:
    Real:
      category: A2
      hash:
      - current_version
      n_images: 267
      split: val
      versions:
      - A
      - B
      - C
  FOST:
    Real:
      category: D1
      hash:
      - current_version
      n_images: 372
      split: val
      versions:
      - A
      - B
  GPST:
    Real:
      category: D1
      hash:
      - current_version
      n_images: 38
      split: val
      versions:
      - A
  Good:
    Real:
      category: Good
      hash:
      - current_version
      n_images: 21840
      split: val
      versions:
      - A
      - B
      - C
      - D
      - E
  MESM:
    Real:
      category: B2
      hash:
      - current_version
      n_images: 38
      split: val
      versions:
      - A
  MSF:
    Real:
      category: B1
      hash:
      - current_version
      n_images: 120
      split: val
      versions:
      - A
  MST:
    Real:
      category: B1
      hash:
      - current_version
      n_images: 90
      split: val
      versions:
      - A
  PST:
    Real:
      category: G1
      hash:
      - current_version
      n_images: 24
      split: val
      versions:
      - A
      - B
      - C
      - D
  SSNPDNeck:
    Real:
      category: C2
      hash:
      - current_version
      n_images: 34
      split: val
      versions:
      - A
      - C
      - D
