test:
  B:
    Real:
      category: A2
      hash:
      - current_version
      n_images: 894
      split: test
      versions:
      - A
      - B
      - C
      - D
      - E
  CCD:
    Real:
      category: A3
      hash:
      - current_version
      n_images: 2100
      split: test
      versions:
      - A
      - B
      - C
      - D
      - E
      - F
      - G
      - H
      - I
  CnC:
    Real:
      category: A1
      hash:
      - current_version
      n_images: 960
      split: test
      versions:
      - A
      - B
      - C
  DPPST:
    Real:
      category: D1
      hash:
      - current_version
      n_images: 203
      split: test
      versions:
      - A
      - B
  FCC:
    Real:
      category: A2
      hash:
      - current_version
      n_images: 1039
      split: test
      versions:
      - A
      - B
      - C
  GPST:
    Real:
      category: D1
      hash:
      - current_version
      n_images: 183
      split: test
      versions:
      - A
  Good:
    Real:
      category: Good
      hash:
      - current_version
      n_images: 21720
      split: test
      versions:
      - A
      - B
      - C
      - D
      - E
  MSF:
    Real:
      category: B1
      hash:
      - current_version
      n_images: 480
      split: test
      versions:
      - A
  SSNPDNeck:
    Real:
      category: C2
      hash:
      - current_version
      n_images: 260
      split: test
      versions:
      - A
      - C
      - D
train:
  B:
    Synthetic:
      category: A2
      hash:
      - v0.1 - beak - fc348f8
      n_images: 2263
      split: synthTrain
      versions: []
  CCD:
    Synthetic:
      category: A3
      hash:
      - v5
      n_images: 2489
      split: synthTrain
      versions: []
  CnC:
    Synthetic:
      category: A1
      hash:
      - v0.1 - HEAD - 8d9eecd
      n_images: 999
      split: synthTrain
      versions: []
  DPPST:
    Synthetic:
      category: D1
      hash:
      - v0.1 - NewParticleStopper - 0466cf31
      n_images: 4996
      split: synthTrain
      versions: []
  FCC:
    Synthetic:
      category: A2
      hash:
      - v0.1 - A1A2merged - 8d9eecd
      n_images: 999
      split: synthTrain
      versions: []
  GPST:
    Synthetic:
      category: D1
      hash:
      - v0.1 - gpst - 59f35e4
      - v0.1 - NewParticleStopper - 0466cf31
      n_images: 8093
      split: synthTrain
      versions: []
  Good:
    Real:
      category: Good
      hash:
      - current_version
      n_images: 171870
      split: train
      versions:
      - A
      - B
      - C
      - D
      - E
  MSF:
    Synthetic:
      category: B1
      hash:
      - v0.1 - main - 8e82c19
      n_images: 1994
      split: synthTrain
      versions: []
  SSNPDNeck:
    Synthetic:
      category: C2
      hash:
      - v0.1 - SSNPDCake - 2b02fc5
      - v0.1 - SSNPDCake - 700e8ce
      n_images: 3024
      split: synthTrain
      versions: []
val:
  B:
    Synthetic:
      category: A2
      hash:
      - v0.1 - beak - fc348f8
      n_images: 653
      split: synthVal
      versions: []
  CCD:
    Synthetic:
      category: A3
      hash:
      - v5
      n_images: 1942
      split: synthVal
      versions: []
  CnC:
    Synthetic:
      category: A1
      hash:
      - v0.1 - HEAD - 8d9eecd
      n_images: 238
      split: synthVal
      versions: []
  DPPST:
    Synthetic:
      category: D1
      hash:
      - v0.1 - NewParticleStopper - 0466cf31
      n_images: 1552
      split: synthVal
      versions: []
  FCC:
    Synthetic:
      category: A2
      hash:
      - v0.1 - A1A2merged - 8d9eecd
      n_images: 284
      split: synthVal
      versions: []
  GPST:
    Synthetic:
      category: D1
      hash:
      - v0.1 - gpst - 59f35e4
      - v0.1 - NewParticleStopper - 0466cf31
      n_images: 2218
      split: synthVal
      versions: []
  Good:
    Real:
      category: Good
      hash:
      - current_version
      n_images: 21840
      split: val
      versions:
      - A
      - B
      - C
      - D
      - E
  MSF:
    Synthetic:
      category: B1
      hash:
      - v0.1 - main - 8e82c19
      n_images: 507
      split: synthVal
      versions: []
  SSNPDNeck:
    Synthetic:
      category: C2
      hash:
      - v0.1 - SSNPDCake - 2b02fc5
      - v0.1 - SSNPDCake - 700e8ce
      n_images: 977
      split: synthVal
      versions: []
