test:
  Good:
    Real:
      category: Good
      hash:
      - current_version
      n_images: 3960
      split: test
      versions:
      - A
train:
  Good:
    Real:
      category: Good
      hash:
      - current_version
      n_images: 31470
      split: train
      versions:
      - A
val:
  Good:
    Real:
      category: Good
      hash:
      - current_version
      n_images: 3930
      split: val
      versions:
      - A