train:
  B:
    Real:
      category: A2
      hash:
      - current_version
      n_images: 789
      split: val
      versions:
      - A
      - B
      - C
      - D
      - E
  CCD:
    Real:
      category: A3
      hash:
      - current_version
      n_images: 1890
      split: val
      versions:
      - A
      - C
      - D
      - E
      - F
      - G
      - I
  ChipSh:
    Real:
      category: C1
      hash:
      - current_version
      n_images: 52
      split: val
      versions:
      - A
      - C
  CnC:
    Real:
      category: A1
      hash:
      - current_version
      n_images: 888
      split: val
      versions:
      - A
      - B
  DIST:
    Real:
      category: B2
      hash:
      - current_version
      n_images: 515
      split: val
      versions:
      - A
      - E
  DPPST:
    Real:
      category: D1
      hash:
      - current_version
      n_images: 170
      split: val
      versions:
      - A
      - B
  FCC:
    Real:
      category: A2
      hash:
      - current_version
      n_images: 982
      split: val
      versions:
      - A
      - B
      - C
  FMI:
    Real:
      category: D1
      hash:
      - current_version
      n_images: 38
      split: val
      versions:
      - A
      - B
  FMOV:
    Real:
      category: C2
      hash:
      - current_version
      n_images: 285
      split: val
      versions:
      - A
      - E
  FOST:
    Real:
      category: D1
      hash:
      - current_version
      n_images: 1515
      split: val
      versions:
      - A
      - B
  GPST:
    Real:
      category: D1
      hash:
      - current_version
      n_images: 152
      split: val
      versions:
      - A
  Good:
    Real:
      category: Good
      hash:
      - current_version
      n_images: 3990
      split: val
      versions:
      - A
  ICFC:
    Real:
      category: A2
      hash:
      - current_version
      n_images: 900
      split: val
      versions:
      - A
      - B
      - C
  LCC:
    Real:
      category: A1
      hash:
      - current_version
      n_images: 1105
      split: val
      versions:
      - A
      - B
  MESM:
    Real:
      category: B2
      hash:
      - current_version
      n_images: 115
      split: val
      versions:
      - A
  MSF:
    Real:
      category: B1
      hash:
      - current_version
      n_images: 480
      split: val
      versions:
      - A
  MST:
    Real:
      category: B1
      hash:
      - current_version
      n_images: 450
      split: val
      versions:
      - A
  PST:
    Real:
      category: G1
      hash:
      - current_version
      n_images: 180
      split: val
      versions:
      - A
      - D
  SSNPDNeck:
    Real:
      category: C2
      hash:
      - current_version
      n_images: 241
      split: val
      versions:
      - A
      - C
      - D

val:
  B:
    Real:
      category: A2
      hash:
      - current_version
      n_images: 789
      split: val
      versions:
      - A
      - B
      - C
      - D
      - E
  CCD:
    Real:
      category: A3
      hash:
      - current_version
      n_images: 1890
      split: val
      versions:
      - A
      - C
      - D
      - E
      - F
      - G
      - I
  ChipSh:
    Real:
      category: C1
      hash:
      - current_version
      n_images: 52
      split: val
      versions:
      - A
      - C
  CnC:
    Real:
      category: A1
      hash:
      - current_version
      n_images: 888
      split: val
      versions:
      - A
      - B
  DIST:
    Real:
      category: B2
      hash:
      - current_version
      n_images: 515
      split: val
      versions:
      - A
      - E
  DPPST:
    Real:
      category: D1
      hash:
      - current_version
      n_images: 170
      split: val
      versions:
      - A
      - B
  FCC:
    Real:
      category: A2
      hash:
      - current_version
      n_images: 982
      split: val
      versions:
      - A
      - B
      - C
  FMI:
    Real:
      category: D1
      hash:
      - current_version
      n_images: 38
      split: val
      versions:
      - A
      - B
  FMOV:
    Real:
      category: C2
      hash:
      - current_version
      n_images: 285
      split: val
      versions:
      - A
      - E
  FOST:
    Real:
      category: D1
      hash:
      - current_version
      n_images: 1515
      split: val
      versions:
      - A
      - B
  GPST:
    Real:
      category: D1
      hash:
      - current_version
      n_images: 152
      split: val
      versions:
      - A
  Good:
    Real:
      category: Good
      hash:
      - current_version
      n_images: 3990
      split: val
      versions:
      - A
  ICFC:
    Real:
      category: A2
      hash:
      - current_version
      n_images: 900
      split: val
      versions:
      - A
      - B
      - C
  LCC:
    Real:
      category: A1
      hash:
      - current_version
      n_images: 1105
      split: val
      versions:
      - A
      - B
  MESM:
    Real:
      category: B2
      hash:
      - current_version
      n_images: 115
      split: val
      versions:
      - A
  MSF:
    Real:
      category: B1
      hash:
      - current_version
      n_images: 480
      split: val
      versions:
      - A
  MST:
    Real:
      category: B1
      hash:
      - current_version
      n_images: 450
      split: val
      versions:
      - A
  PST:
    Real:
      category: G1
      hash:
      - current_version
      n_images: 180
      split: val
      versions:
      - A
      - D
  SSNPDNeck:
    Real:
      category: C2
      hash:
      - current_version
      n_images: 241
      split: val
      versions:
      - A
      - C
      - D
